components:
  schemas:
    Genre:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        bio:
          type: string
          nullable: true
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        year:
          type: integer
          nullable: true
        author_id:
          type: integer
        genre_id:
          type: integer
        author:
          type: string
          nullable: true
        genre:
          type: string
          nullable: true
    Error:
      type: object
      properties:
        error:
          type: string
